name: Hello
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world
        id: hello
        uses: ./.github/actions/hello-world
        with:
          who-to-greet: 'nnaata'
      - name: Get the output time
        run: echo "The time was  ${{ steps.hello.outputs.time }}"